# Generated by Django 2.1.5 on 2019-03-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensor_name', models.CharField(max_length=200)),
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('power', models.IntegerField()),
                ('current', models.IntegerField()),
                ('voltage', models.IntegerField()),
            ],
            options={
                'ordering': ['data_id'],
            },
        ),
    ]
