# Generated by Django 2.1.5 on 2019-03-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybuildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(default='floor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='room', max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuildings.Floor')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='current',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='voltage',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mybuildings.Floor'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mybuildings.Room'),
        ),
    ]
